language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get install poppler-utils
  - pip3 install --upgrade pip setuptools wheel
  - sudo apt install tesseract-ocr
  - git clone https://github.com/Layout-Parser/layout-parser.git
install:
  - pip install Pillow
  - pip install torch
  - pip install psutil
  - pip install memory_profiler
  - pip install codecov
  - pip install pdf2image
  - pip install -U layoutparser
  - pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.4#egg=detectron2' 
  - pip install layoutparser[ocr]